export const FINANCE_TRANSACTIONS_LOAD = "FINANCE_TRANSACTIONS_LOAD";
export const FINANCE_TRANSACTIONS_GET = 'FINANCE_TRANSACTIONS_GET'
export const FINANCE_TRANSACTIONS_FILTER = 'FINANCE_TRANSACTIONS_FILTER'