export const MATKA_GAMES_GET_DATA = "MATKA_GAMES_GET_DATA";
export const MATKA_GAMES_PAGENATION = "MATKA_GAMES_PAGENATION";
export const MATKA_GAMES_FILTER_DATA = "MATKA_GAMES_FILTER_DATA";
export const MATKA_GAMES_GMAELIST_DATA = "MATKA_GAMES_GMAELIST_DATA";

export const MATKA_BAZAARS_GET_DATA = "MATKA_BAZAARS_GET_DATA";
export const MATKA_BAZAARS_PAGENATION = "MATKA_BAZAARS_PAGENATION";
export const MATKA_BAZAARS_FILTER_DATA = "MATKA_BAZAARS_FILTER_DATA";

export const MATKA_ANOUNCER_GET_DATA = "MATKA_ANOUNCER_GET_DATA";
export const MATKA_ANOUNCER_PAGENATION = "MATKA_ANOUNCER_PAGENATION";
export const MATKA_ANOUNCER_FILTER_DATA = "MATKA_ANOUNCER_FILTER_DATA";


export const MATKA_RESULT_GET_DATA = "MATKA_RESULT_GET_DATA";
export const MATKA_RESULT_PAGENATION = "MATKA_RESULT_PAGENATION";
export const MATKA_RESULT_FILTER_DATA = "MATKA_RESULT_FILTER_DATA";
export const MATKA_RESULT_BAZAARLIST_DATA = "MATKA_RESULT_BAZAARLIST_DATA";