export const REPORTSCASINO_GAMEID_LOAD = "REPORTSCASINO_GAMEID_LOAD";
export const REPORTSCASINO_GAMEID_GETDATA = "REPORTSCASINO_GAMEID_GETDATA";
export const REPORTSCASINO_GAMEID_PROVIDER = "REPORTSCASINO_GAMEID_PROVIDER";


export const REPORTSCASINO_PLAYERID_LOAD = "REPORTSCASINO_PLAYERID_LOAD";
export const REPORTSCASINO_PLAYERID_GETDATA = "REPORTSCASINO_PLAYERID_GETDATA";
export const REPORTSCASINO_PLAYERID_FILTER = "REPORTSCASINO_PLAYERID_FILTER";

export const REPORTSCASINO_PROVIDERS_LOAD = "REPORTSCASINO_PROVIDERS_LOAD";
export const REPORTSCASINO_PROVIDERS_GETDATA = "REPORTSCASINO_PROVIDERS_GETDATA";
export const REPORTSCASINO_PROVIDERS_FILTER = "REPORTSCASINO_PLAYERID_FILTER";
export const REPORTSCASINO_PROVIDERS_PROVIDERS = "REPORTSCASINO_PROVIDERS_PROVIDERS";

export const REPORTSCASINO_GAMEPLAYER_LOAD = "REPORTSCASINO_GAMEPLAYER_LOAD";
export const REPORTSCASINO_GAMEPLAYER_GETDATA = "REPORTSCASINO_GAMEPLAYER_GETDATA";
export const REPORTSCASINO_GAMEPLAYER_PROVIDER = "REPORTSCASINO_GAMEPLAYER_PROVIDER";
